# Use an official Node runtime as the base image
FROM node:18.16-alpine3.18
WORKDIR /app
COPY . .
RUN npm i

WORKDIR /app/Api
EXPOSE 3551
CMD [ "npm", "run", "start" ]

# Run the app when the container launches
