networks:
  stmp-net:
    name: stmp-net

services:
  front-end:
    build:
      context: ./Front-end
      # dockerfile: ./Portal/DockerFile
      dockerfile: ./DockerFile-Front-End
    restart: unless-stopped
    ports:
      # - "3000:3000" #use if the port is used by an other container
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3551
    networks:
      - stmp-net
    volumes:
      - ./Front-end:/app
      # - /app/node_modules

  portal:
    build:
      context: .
      dockerfile: ./DockerFile-Portal
    restart: unless-stopped
    ports:
      - "3550:3550"
    volumes:
      - ./Portal/src:/app/Portal/src # For developmennt purposes

  api:
    build:
      context: .
      dockerfile: DockerFile-Api
    restart: unless-stopped
    command: [ "npm", "run", "dev" ]
    ports:
      - "3551:3551"
    networks:
      - stmp-net
    volumes:
      - ./Api/src:/app/Api/src # For developmennt purposes
    depends_on:
      - stmp-db
    env_file:
      - Api/.env.dev

  stmp-db:
    container_name: stmp-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3552:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - stmp-net
