FROM node:20.19.0-alpine AS builder
WORKDIR /app
COPY ./shared-lib /app/shared-lib
COPY ./Portal /app/Portal
COPY ./Portal/.env.dev /app/Portal/.env

WORKDIR /app/Portal
RUN npm i 

EXPOSE 3550

CMD [ "npm", "run", "dev", "--", "--host"]