version: "3.9"

networks:
  stmp-net:
    name: stmp-net

services:
  front-end:
    build:
      context: ./Front-end
      dockerfile: ../DockerFile-Front-End
      args:
        VITE_API_BASE_URL: /api
    restart: unless-stopped
    networks:
      - stmp-net
    # Static nginx serves on 80 inside container

  portal:
    build:
      context: .
      dockerfile: DockerFile-Portal-prod
    restart: unless-stopped
    networks:
      - stmp-net
    environment:
      - PORT=3550
      - HOST=0.0.0.0

  api:
    build:
      context: .
      dockerfile: DockerFile-Api-prod
    restart: unless-stopped
    command: ["npm", "run", "start"]
    networks:
      - stmp-net
    depends_on:
      - stmp-db
    env_file:
      - ./Api/.env.prod

  stmp-db:
    container_name: stmp-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=U3QgTWljaGVsIEtpZ2FsaGVy
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - stmp-net

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front-end
      - portal
      - api
    networks:
      - stmp-net
