# Use an official Node runtime as the base image
FROM node:20.15.0-alpine AS builder
WORKDIR /app
COPY ./shared-lib /app/shared-lib
COPY ./Api /app/Api
COPY ./Api/.env.prod /app/Api/.env

WORKDIR /app/Api
RUN npm i 

EXPOSE 3551
