# Use an official Node runtime as the base image
FROM node:20.15.0-alpine AS builder
WORKDIR /app
COPY ./shared-lib /app/shared-lib
COPY ./Api /app/Api
COPY ./Api/.env.docker /app/Api/.env

WORKDIR /app/Api
RUN npm i --save

EXPOSE 3551
CMD [ "npm", "run", "start" ]

# Run the app when the container launches
