version: '3.8'
networks:
  stmp-net:
    name: stmp-net

services:
  api:
    build:
      context: .
      dockerfile: ./Api/Dockerfile
    restart: unless-stopped
    # command: ["npm", "run", "start"]
    ports:
      - "3551:3551"
    networks:
      - stmp-net

    depends_on:
      - stmp-db
      # - minio
  
  stmp-db:
    container_name: stmp-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    # restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3552:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
      # - data:/data/db
    networks:
      - stmp-net