FROM node:20.15.0-alpine AS builder
WORKDIR /app

COPY Portal ./Portal
COPY shared-lib ./shared-lib
COPY Portal/.env.prod ./Portal/.env

WORKDIR /app/Portal
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/Portal/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3550
CMD ["nginx", "-g", "daemon off;"]
