    # ---------- Build Stage ----------
FROM node:20.15.0-alpine AS builder
WORKDIR /app

# Build shared-lib first
COPY ./shared-lib /app/shared-lib
WORKDIR /app/shared-lib
RUN npm ci && npm run build

# Copy and build Portal
COPY ./Portal /app/Portal
COPY ./Portal/.env.prod /app/Portal/.env
WORKDIR /app/Portal
RUN npm ci && npm run build

# ---------- Runtime Stage ----------
FROM nginx:stable-alpine
# Copy build output from builder stage
COPY --from=builder /app/Portal/dist /usr/share/nginx/html
# Copy custom nginx configuration
COPY ./Portal/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3550
CMD ["nginx", "-g", "daemon off;"]
