# Use an official Node runtime as the base image
FROM node:18.16-alpine AS builder
WORKDIR /app
COPY ./shared-lib /app/shared-lib
COPY ./Api /app/Api

WORKDIR /app/Api
RUN npm i 
# RUN npm i ts-node --save-dev
# RUN npm i @types/bcrypt --save-dev
# RUN npm i --save bcrypt 

EXPOSE 3551
# CMD [ "npm", "run", "start" ]

# Run the app when the container launches
