# Use official Node.js image as a base
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and lock file
COPY package.json package-lock.json ./

# Install dependencies with npm
RUN npm ci --only=production

# Copy the rest of the project files
COPY . .

# Build Next.js app
RUN npm run build

# Use a smaller image for the final production build
FROM node:18-alpine AS runner

# Set working directory
WORKDIR /app

# Copy the built files from the builder
COPY --from=builder /app ./

# Expose port 3000
EXPOSE 3000

# Start Next.js app
CMD ["npm", "start"]
