import swaggerJSDoc from 'swagger-jsdoc'
import path from 'path'
import fs from 'fs'
import yaml from 'js-yaml'
import { cloneDeep } from 'lodash'

const ROUTE_PATH = path.join(__dirname, '../routes/**/*.ts')
const ENTITY_PATH = path.join(__dirname, '../entity/**/*.ts')

const options = {
  failOnErrors: true,
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'St Michel Website API',
      version: '0.1.0',
      // eslint-disable-next-line max-len
      description: 'St Michel Website Backend'
    },
    servers: [
      {
        url: '/api'
      }
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        }
      }
    },
    security: [
      {
        bearerAuth: []
      }
    ]
  },
  apis: [ROUTE_PATH, ENTITY_PATH]
}

const generatedSwagger = swaggerJSDoc(options)

export const openAPISpecification: any = cloneDeep(generatedSwagger)

const tagOrder = [
  "Choir",
  "Commission",
  "Community",
  "Fronted",
  "Images",
  "Language",
  "Location",
  "Mass Times",
  "Mpuza Miryango Remezo",
  "Muryango Remezo",
  "Office Hours",
  "Parish History",
  "Priests",
  "Recent Events",
  "Services",
  "Top News And Notices",
  "Users",
  "Welcome Message",
  "parishCommitteeCouncil"
];

openAPISpecification.tags.sort((a: { name: string }, b: { name: string }) => {
  const indexA = tagOrder.indexOf(a.name)
  const indexB = tagOrder.indexOf(b.name)

  const aNotFound = indexA === -1
  const bNotFound = indexB === -1

  if (aNotFound && bNotFound) {
    return a.name.localeCompare(b.name) // fallback alphabetical order
  }
  if (aNotFound) return 1  // unknown tags go to the end
  if (bNotFound) return -1
  return indexA - indexB
})

fs.writeFileSync(
  path.join(__dirname, '../docs/openapi-autogenerated.yaml'),
  yaml.dump(openAPISpecification)
)
