export * from './homePage/HomePage'
export * from './aboutPage/AboutPage'
export * from './contactPage/ContactPage'
export * from './servicePage/ServicePage'
export * from './aboutPage/Chorals'
export * from './aboutPage/ChoralDetails'
export * from './NotFoundPage'
export * from './aboutPage/CatholicAction'
export * from './aboutPage/CommunityPage'
export * from './aboutPage/ParishCommitteePage'
export * from './servicePage/MassSchedulePage'
export * from './servicePage/SacramentsPage'
export * from './servicePage/ServicesOfficePage'
// export * from './servicePage/ServiceDetailsWrapper'
export * from './servicePage/ServicesListPage'